name1 = str('sydney')
name2 = str('brooklyn')
print(''.join(reversed(name1)))
print(''.join(reversed(name2)))
print(name1.upper())
print(len(name1))
names = list()
names.append('sydney')
names.append('brooklyn')
print(names)
print(', '.join(names))
